#!/usr/bin/env php
<?php
ini_set('memory_limit', '16M');

use Click\MeasurementCalculator\Application\MeasurementCalculator;
use Click\MeasurementCalculator\Infrastructure\Csv\CommonCsvGateway;
use Click\MeasurementCalculator\Infrastructure\FileSystem\RecursiveFileNameFetcher;

require __DIR__ . '/vendor/autoload.php';

$temporaryDirectory = 'tmp';
$outputFilename = 'output.csv';

if (!file_exists($temporaryDirectory)) {
    mkdir($temporaryDirectory);
}

if (file_exists($outputFilename)) {
    unlink($outputFilename);
}

$recursiveFileNameFetcher = new RecursiveFileNameFetcher();
$csvCommonGateway = new CommonCsvGateway($outputFilename, $temporaryDirectory, $recursiveFileNameFetcher);
$calculator = new MeasurementCalculator($recursiveFileNameFetcher, $csvCommonGateway, $csvCommonGateway, $csvCommonGateway);

$calculator->calculate(realpath($_SERVER['argv'][1]));

exec('rm -rf ' . realpath($temporaryDirectory));
